const crypto = require("crypto");
const { PutCommand } = require("@aws-sdk/lib-dynamodb");
const { docClient, tableNames } = require("./dynamodb.cjs");

const now = "2026-04-22T10:30:00.000Z";

function hashPassword(password) {
  return crypto.createHash("sha256").update(password).digest("hex");
}

const users = [
  {
    usernameKey: "admin",
    userId: "user-admin",
    username: "Admin",
    displayName: "Admin",
    role: "admin",
    balance: 0,
    passwordHash: hashPassword("Admin"),
    createdAt: now,
  },
  {
    usernameKey: "kjell",
    userId: "user-kjell",
    username: "kjell",
    displayName: "Kjell Fiebiger",
    role: "user",
    balance: 15,
    passwordHash: hashPassword("test123"),
    createdAt: now,
  },
  {
    usernameKey: "ramona",
    userId: "user-ramona",
    username: "ramona",
    displayName: "Ramona Buchbinder",
    role: "user",
    balance: 8.5,
    passwordHash: hashPassword("test123"),
    createdAt: now,
  },
];

const categories = [
  {
    categoryId: "cat-fiction",
    name: "Roman",
    description: "Literarische und unterhaltende Belletristik",
    shelf: "A1",
    createdAt: now,
  },
  {
    categoryId: "cat-it",
    name: "Informatik",
    description: "Programmierung, Datenbanken und IT-Systeme",
    shelf: "B2",
    createdAt: now,
  },
  {
    categoryId: "cat-business",
    name: "Wirtschaft",
    description: "Management, Rechnungswesen und Organisation",
    shelf: "C1",
    createdAt: now,
  },
  {
    categoryId: "cat-science",
    name: "Wissenschaft",
    description: "Naturwissenschaften und Technik",
    shelf: "D3",
    createdAt: now,
  },
];

const members = [
  {
    memberId: "member-kjell",
    firstName: "Kjell",
    lastName: "Fiebiger",
    email: "kjell@example.local",
    role: "Student",
    balance: 15,
    activeLoanIds: ["loan-001", "loan-003"],
    createdAt: now,
  },
  {
    memberId: "member-ramona",
    firstName: "Ramona",
    lastName: "Buchbinder",
    email: "ramona@example.local",
    role: "Studentin",
    balance: 8.5,
    activeLoanIds: ["loan-002"],
    createdAt: now,
  },
  {
    memberId: "member-maria",
    firstName: "Maria",
    lastName: "Schneider",
    email: "maria@example.local",
    role: "Dozentin",
    balance: 23,
    activeLoanIds: [],
    createdAt: now,
  },
  {
    memberId: "member-tom",
    firstName: "Tom",
    lastName: "Weber",
    email: "tom@example.local",
    role: "Gast",
    balance: 4,
    activeLoanIds: [],
    createdAt: now,
  },
];

const books = [
  {
    bookId: "book-clean-code",
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "9780132350884",
    year: "2008",
    category: "Informatik",
    categoryId: "cat-it",
    available: false,
    borrowerName: "Kjell Fiebiger",
    borrowedAt: "2026-04-10T09:15:00.000Z",
    averageRating: 4.8,
    reviewIds: ["review-001", "review-002"],
    createdAt: now,
  },
  {
    bookId: "book-dynamodb",
    title: "Amazon DynamoDB Guide",
    author: "AWS",
    isbn: "9780000000001",
    year: "2024",
    category: "Informatik",
    categoryId: "cat-it",
    available: false,
    borrowerName: "Ramona Buchbinder",
    borrowedAt: "2026-04-12T14:00:00.000Z",
    averageRating: 4.5,
    reviewIds: ["review-003"],
    createdAt: now,
  },
  {
    bookId: "book-node-express",
    title: "Node.js und Express kompakt",
    author: "Lena Hoffmann",
    isbn: "9783000000002",
    year: "2023",
    category: "Informatik",
    categoryId: "cat-it",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 4.2,
    reviewIds: ["review-004"],
    createdAt: now,
  },
  {
    bookId: "book-datenbanken",
    title: "NoSQL Datenbanken verstehen",
    author: "Martin Keller",
    isbn: "9783000000003",
    year: "2022",
    category: "Informatik",
    categoryId: "cat-it",
    available: false,
    borrowerName: "Kjell Fiebiger",
    borrowedAt: "2026-03-28T11:30:00.000Z",
    averageRating: 4.6,
    reviewIds: ["review-005"],
    createdAt: now,
  },
  {
    bookId: "book-projektmanagement",
    title: "Projektmanagement Grundlagen",
    author: "Sabine Richter",
    isbn: "9783000000004",
    year: "2021",
    category: "Wirtschaft",
    categoryId: "cat-business",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 3.9,
    reviewIds: ["review-006"],
    createdAt: now,
  },
  {
    bookId: "book-faust",
    title: "Faust",
    author: "Johann Wolfgang von Goethe",
    isbn: "9783150000014",
    year: "1808",
    category: "Roman",
    categoryId: "cat-fiction",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 4.1,
    reviewIds: ["review-007"],
    createdAt: now,
  },
  {
    bookId: "book-physik",
    title: "Physik fuer Einsteiger",
    author: "Nina Brandt",
    isbn: "9783000000005",
    year: "2020",
    category: "Wissenschaft",
    categoryId: "cat-science",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 3.7,
    reviewIds: [],
    createdAt: now,
  },
  {
    bookId: "book-controlling",
    title: "Controlling im Mittelstand",
    author: "Jens Bauer",
    isbn: "9783000000006",
    year: "2019",
    category: "Wirtschaft",
    categoryId: "cat-business",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 4.0,
    reviewIds: [],
    createdAt: now,
  },
  {
    bookId: "book-asoiaf-01-game-of-thrones",
    title: "A Game of Thrones",
    author: "George R. R. Martin",
    isbn: "9780553103540",
    year: "1996",
    category: "Roman",
    categoryId: "cat-fiction",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 4.7,
    reviewIds: [],
    createdAt: now,
  },
  {
    bookId: "book-asoiaf-02-clash-of-kings",
    title: "A Clash of Kings",
    author: "George R. R. Martin",
    isbn: "9780553108033",
    year: "1999",
    category: "Roman",
    categoryId: "cat-fiction",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 4.6,
    reviewIds: [],
    createdAt: now,
  },
  {
    bookId: "book-asoiaf-03-storm-of-swords",
    title: "A Storm of Swords",
    author: "George R. R. Martin",
    isbn: "9780553106633",
    year: "2000",
    category: "Roman",
    categoryId: "cat-fiction",
    available: false,
    borrowerName: "Ramona Buchbinder",
    borrowedAt: "2026-04-18T15:45:00.000Z",
    averageRating: 4.8,
    reviewIds: [],
    createdAt: now,
  },
  {
    bookId: "book-asoiaf-04-feast-for-crows",
    title: "A Feast for Crows",
    author: "George R. R. Martin",
    isbn: "9780553801507",
    year: "2005",
    category: "Roman",
    categoryId: "cat-fiction",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 4.2,
    reviewIds: [],
    createdAt: now,
  },
  {
    bookId: "book-asoiaf-05-dance-with-dragons",
    title: "A Dance with Dragons",
    author: "George R. R. Martin",
    isbn: "9780553801477",
    year: "2011",
    category: "Roman",
    categoryId: "cat-fiction",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 4.3,
    reviewIds: [],
    createdAt: now,
  },
  {
    bookId: "book-asoiaf-world-of-ice-and-fire",
    title: "The World of Ice & Fire",
    author: "George R. R. Martin",
    isbn: "9780553805444",
    year: "2014",
    category: "Roman",
    categoryId: "cat-fiction",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 4.4,
    reviewIds: [],
    createdAt: now,
  },
  {
    bookId: "book-asoiaf-knight-seven-kingdoms",
    title: "A Knight of the Seven Kingdoms",
    author: "George R. R. Martin",
    isbn: "9780345533487",
    year: "2015",
    category: "Roman",
    categoryId: "cat-fiction",
    available: false,
    borrowerName: "Kjell Fiebiger",
    borrowedAt: "2026-04-20T10:10:00.000Z",
    averageRating: 4.5,
    reviewIds: [],
    createdAt: now,
  },
  {
    bookId: "book-asoiaf-fire-and-blood",
    title: "Fire & Blood",
    author: "George R. R. Martin",
    isbn: "9781524796280",
    year: "2018",
    category: "Roman",
    categoryId: "cat-fiction",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 4.1,
    reviewIds: [],
    createdAt: now,
  },
  {
    bookId: "book-asoiaf-rise-of-the-dragon",
    title: "The Rise of the Dragon",
    author: "George R. R. Martin",
    isbn: "9781984859259",
    year: "2022",
    category: "Roman",
    categoryId: "cat-fiction",
    available: true,
    borrowerName: "",
    borrowedAt: "",
    averageRating: 4.0,
    reviewIds: [],
    createdAt: now,
  },
];

const loans = [
  {
    loanId: "loan-001",
    bookId: "book-clean-code",
    memberId: "member-kjell",
    borrowerName: "Kjell Fiebiger",
    borrowedAt: "2026-04-10T09:15:00.000Z",
    dueAt: "2026-04-24T09:15:00.000Z",
    returnedAt: "",
    status: "active",
    extensionCount: 0,
    dailyLateFee: 0.5,
  },
  {
    loanId: "loan-002",
    bookId: "book-dynamodb",
    memberId: "member-ramona",
    borrowerName: "Ramona Buchbinder",
    borrowedAt: "2026-04-12T14:00:00.000Z",
    dueAt: "2026-04-26T14:00:00.000Z",
    returnedAt: "",
    status: "active",
    extensionCount: 1,
    dailyLateFee: 0.5,
  },
  {
    loanId: "loan-003",
    bookId: "book-datenbanken",
    memberId: "member-kjell",
    borrowerName: "Kjell Fiebiger",
    borrowedAt: "2026-03-28T11:30:00.000Z",
    dueAt: "2026-04-11T11:30:00.000Z",
    returnedAt: "",
    status: "overdue",
    extensionCount: 0,
    dailyLateFee: 0.5,
  },
  {
    loanId: "loan-004",
    bookId: "book-faust",
    memberId: "member-maria",
    borrowerName: "Maria Schneider",
    borrowedAt: "2026-03-01T08:00:00.000Z",
    dueAt: "2026-03-15T08:00:00.000Z",
    returnedAt: "2026-03-13T16:20:00.000Z",
    status: "returned",
    extensionCount: 0,
    dailyLateFee: 0.5,
  },
  {
    loanId: "loan-005",
    bookId: "book-projektmanagement",
    memberId: "member-tom",
    borrowerName: "Tom Weber",
    borrowedAt: "2026-02-15T10:00:00.000Z",
    dueAt: "2026-03-01T10:00:00.000Z",
    returnedAt: "2026-03-05T09:00:00.000Z",
    status: "returned-late",
    extensionCount: 0,
    dailyLateFee: 0.5,
  },
];

const ownerByBookId = {
  "book-dynamodb": ["user-ramona", "Ramona Buchbinder"],
  "book-asoiaf-03-storm-of-swords": ["user-ramona", "Ramona Buchbinder"],
  "book-asoiaf-knight-seven-kingdoms": ["user-kjell", "Kjell Fiebiger"],
};

books.forEach((book) => {
  const [ownerId, ownerName] = ownerByBookId[book.bookId] || [
    "user-kjell",
    "Kjell Fiebiger",
  ];

  book.ownerId = ownerId;
  book.ownerName = ownerName;
});

const reviews = [
  {
    reviewId: "review-001",
    bookId: "book-clean-code",
    memberId: "member-kjell",
    rating: 5,
    comment: "Sehr gut fuer saubere Struktur im Code.",
    createdAt: "2026-04-11T12:00:00.000Z",
  },
  {
    reviewId: "review-002",
    bookId: "book-clean-code",
    memberId: "member-maria",
    rating: 4.5,
    comment: "Gut als Referenz fuer Refactoring.",
    createdAt: "2026-04-12T12:00:00.000Z",
  },
  {
    reviewId: "review-003",
    bookId: "book-dynamodb",
    memberId: "member-ramona",
    rating: 4.5,
    comment: "Passt gut zum NoSQL-Projekt.",
    createdAt: "2026-04-13T12:00:00.000Z",
  },
  {
    reviewId: "review-004",
    bookId: "book-node-express",
    memberId: "member-tom",
    rating: 4.2,
    comment: "Praktische Beispiele fuer REST-APIs.",
    createdAt: "2026-04-14T12:00:00.000Z",
  },
  {
    reviewId: "review-005",
    bookId: "book-datenbanken",
    memberId: "member-kjell",
    rating: 4.6,
    comment: "Hilfreich fuer Dokumentverknuepfungen.",
    createdAt: "2026-04-15T12:00:00.000Z",
  },
  {
    reviewId: "review-006",
    bookId: "book-projektmanagement",
    memberId: "member-ramona",
    rating: 3.9,
    comment: "Solide Grundlagen.",
    createdAt: "2026-04-16T12:00:00.000Z",
  },
  {
    reviewId: "review-007",
    bookId: "book-faust",
    memberId: "member-maria",
    rating: 4.1,
    comment: "Klassiker im Roman-Regal.",
    createdAt: "2026-04-17T12:00:00.000Z",
  },
];

const payments = [
  {
    paymentId: "payment-001",
    memberId: "member-kjell",
    type: "topup",
    amount: 20,
    reason: "Guthaben aufgeladen",
    createdAt: "2026-04-01T09:00:00.000Z",
  },
  {
    paymentId: "payment-002",
    memberId: "member-kjell",
    type: "fee",
    amount: -5,
    reason: "Verspaetungsgebuehr",
    loanId: "loan-003",
    createdAt: "2026-04-20T09:00:00.000Z",
  },
  {
    paymentId: "payment-003",
    memberId: "member-ramona",
    type: "topup",
    amount: 10,
    reason: "Guthaben aufgeladen",
    createdAt: "2026-04-03T10:00:00.000Z",
  },
  {
    paymentId: "payment-004",
    memberId: "member-ramona",
    type: "fee",
    amount: -1.5,
    reason: "Reservierung",
    createdAt: "2026-04-08T10:00:00.000Z",
  },
  {
    paymentId: "payment-005",
    memberId: "member-maria",
    type: "topup",
    amount: 25,
    reason: "Guthaben aufgeladen",
    createdAt: "2026-03-10T08:00:00.000Z",
  },
  {
    paymentId: "payment-006",
    memberId: "member-tom",
    type: "fee",
    amount: -2,
    reason: "Verspaetete Rueckgabe",
    loanId: "loan-005",
    createdAt: "2026-03-05T09:05:00.000Z",
  },
];

const seedGroups = [
  [tableNames.users, users],
  [tableNames.categories, categories],
  [tableNames.members, members],
  [tableNames.books, books],
  [tableNames.loans, loans],
  [tableNames.reviews, reviews],
  [tableNames.payments, payments],
];

async function putItems(tableName, items) {
  for (const item of items) {
    await docClient.send(
      new PutCommand({
        TableName: tableName,
        Item: item,
      })
    );
  }

  console.log(`${items.length} Datensaetze in ${tableName} geschrieben.`);
}

async function seedData() {
  for (const [tableName, items] of seedGroups) {
    await putItems(tableName, items);
  }
}

seedData().catch((error) => {
  console.error("Testdaten konnten nicht geschrieben werden:", error.message);
  process.exit(1);
});
